id: P005564
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5344
  title: སྤུ་རྒྱལ་བཙན་པོའི་སྐབས་ཀྱི་བརྡ་རྙིང་ཡིག་ཆ་སློབ་གསར་སྟོང་གི་འཇུག་སྒོ།
  author: ''
  volumes:
    438a3234d6344d4c8e68cd64c350bdfa:
      image_group_id: I1KG5409
      title: ''
      volume_number: 1
      total_pages: 430
      base_file: v001.txt
